# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161101_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplanfile',
            name='student_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_plan_file', to='users.StudentPlan'),
        ),
    ]
