# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161101_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplan',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
