# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161101_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpracticelog',
            name='practice_category',
            field=models.CharField(blank=True, choices=[('LEAD_TECHNIQUE', 'Lead Technique'), ('RHYTHM_TECHNIQUE', 'Rhythm Technique'), ('FRETBOARD', 'Fretboard Knowledge'), ('THEORY', 'Music Theory Concepts'), ('REPERTOIRE', 'Songs and Repertoire'), ('CREATIVITY', 'Creativity')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='play_level',
            field=models.CharField(blank=True, choices=[('1', 'White'), ('2', 'Yellow'), ('3', 'Orange'), ('4', 'Green'), ('5', 'Blue'), ('6', 'Purple'), ('7', 'Red'), ('8', 'Brown'), ('9', 'Black')], default='1', max_length=20, null=True),
        ),
    ]
