# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161120_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentplan',
            name='students',
        ),
        migrations.AddField(
            model_name='user',
            name='student_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_student', to='users.StudentPlan'),
        ),
    ]
