# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161120_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplansection',
            name='section_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentplansection',
            name='section_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentplansection',
            name='section_title',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
