# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('category_created', models.DateTimeField(auto_now_add=True)),
                ('category_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('message_created', models.DateTimeField(auto_now_add=True)),
                ('message_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_file', models.FileField(blank=True, null=True, upload_to=users.models.get_upload_file_name)),
                ('message_file_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_message', to='forum.Message')),
                ('message_file_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('topic_created', models.DateTimeField(auto_now_add=True)),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_topic', to='forum.Category')),
                ('topic_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_message', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
